package com.elorBase.server.elorBaseServer.dataBase.entity;

import javax.persistence.Entity;
import javax.persistence.Id;

// Generated 27 ene 2025, 17:16:15 by Hibernate Tools 6.5.1.Final

/**
 * Asignatura generated by hbm2java
 */
@Entity
public class Asignatura implements java.io.Serializable {

	@Id
	private String idAsignatura;
	private String nombre;
	private int horasTotales;
	private Integer curso;
	private Integer idProfesor;

	public Asignatura() {
	}

	public Asignatura(String idAsignatura, String nombre, int horasTotales) {
		this.idAsignatura = idAsignatura;
		this.nombre = nombre;
		this.horasTotales = horasTotales;
	}

	public Asignatura(String idAsignatura, String nombre, int horasTotales, Integer curso, Integer idProfesor) {
		this.idAsignatura = idAsignatura;
		this.nombre = nombre;
		this.horasTotales = horasTotales;
		this.curso = curso;
		this.idProfesor = idProfesor;
	}

	public String getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(String idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getHorasTotales() {
		return this.horasTotales;
	}

	public void setHorasTotales(int horasTotales) {
		this.horasTotales = horasTotales;
	}

	public Integer getCurso() {
		return this.curso;
	}

	public void setCurso(Integer curso) {
		this.curso = curso;
	}

	public Integer getIdProfesor() {
		return this.idProfesor;
	}

	public void setIdProfesor(Integer idProfesor) {
		this.idProfesor = idProfesor;
	}

}
