package com.elorBase.server.elorBaseServer.dataBase.entity;
// Generated 27 ene 2025, 17:16:15 by Hibernate Tools 6.5.1.Final

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Cicloformativo generated by hbm2java
 */
@Entity
public class Cicloformativo implements java.io.Serializable {

	@Id
	private String idCiclo;
	private String nombre;

	public Cicloformativo() {
	}

	public Cicloformativo(String idCiclo, String nombre) {
		this.idCiclo = idCiclo;
		this.nombre = nombre;
	}

	public String getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(String idCiclo) {
		this.idCiclo = idCiclo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
