package com.elorBase.server.elorBaseServer.dataBase.entity;
// Generated 27 ene 2025, 17:16:15 by Hibernate Tools 6.5.1.Final

/**
 * FormacionId generated by hbm2java
 */
public class FormacionId implements java.io.Serializable {

	private String idAsignatura;
	private String idCiclo;

	public FormacionId() {
	}

	public FormacionId(String idAsignatura, String idCiclo) {
		this.idAsignatura = idAsignatura;
		this.idCiclo = idCiclo;
	}

	public String getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(String idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

	public String getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(String idCiclo) {
		this.idCiclo = idCiclo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FormacionId))
			return false;
		FormacionId castOther = (FormacionId) other;

		return ((this.getIdAsignatura() == castOther.getIdAsignatura()) || (this.getIdAsignatura() != null
				&& castOther.getIdAsignatura() != null && this.getIdAsignatura().equals(castOther.getIdAsignatura())))
				&& ((this.getIdCiclo() == castOther.getIdCiclo()) || (this.getIdCiclo() != null
						&& castOther.getIdCiclo() != null && this.getIdCiclo().equals(castOther.getIdCiclo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdAsignatura() == null ? 0 : this.getIdAsignatura().hashCode());
		result = 37 * result + (getIdCiclo() == null ? 0 : this.getIdCiclo().hashCode());
		return result;
	}

}
