package com.elorBase.server.elorBaseServer.dataBase.entity;
// Generated 27 ene 2025, 17:16:15 by Hibernate Tools 6.5.1.Final

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Formacion generated by hbm2java
 */
@Entity
public class Formacion implements java.io.Serializable {

	@Id
	private FormacionId id;

	public Formacion() {
	}

	public Formacion(FormacionId id) {
		this.id = id;
	}

	public FormacionId getId() {
		return this.id;
	}

	public void setId(FormacionId id) {
		this.id = id;
	}

}
