package com.elorBase.server.elorBaseServer.dataBase.entity;
// Generated 27 ene 2025, 17:16:15 by Hibernate Tools 6.5.1.Final

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Horario generated by hbm2java
 */
@Entity
public class Horario implements java.io.Serializable {

	@Id
	private Integer idHorario;
	private int hora;
	private String dia;
	private Integer aula;
	private String idAsignatura;

	public Horario() {
	}

	public Horario(int hora, String dia) {
		this.hora = hora;
		this.dia = dia;
	}

	public Horario(int hora, String dia, Integer aula, String idAsignatura) {
		this.hora = hora;
		this.dia = dia;
		this.aula = aula;
		this.idAsignatura = idAsignatura;
	}

	public Integer getIdHorario() {
		return this.idHorario;
	}

	public void setIdHorario(Integer idHorario) {
		this.idHorario = idHorario;
	}

	public int getHora() {
		return this.hora;
	}

	public void setHora(int hora) {
		this.hora = hora;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	public Integer getAula() {
		return this.aula;
	}

	public void setAula(Integer aula) {
		this.aula = aula;
	}

	public String getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(String idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

}
