package com.elorBase.server.elorBaseServer.dataBase.entity;
// Generated 27 ene 2025, 17:16:15 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Matriculacion generated by hbm2java
 */
public class Matriculacion implements java.io.Serializable {

	private int idAlumno;
	private String idCiclo;
	private String modalidad;
	private int curso;
	private Date fecha;

	public Matriculacion() {
	}

	public Matriculacion(int idAlumno, String idCiclo, String modalidad, int curso, Date fecha) {
		this.idAlumno = idAlumno;
		this.idCiclo = idCiclo;
		this.modalidad = modalidad;
		this.curso = curso;
		this.fecha = fecha;
	}

	public int getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(int idAlumno) {
		this.idAlumno = idAlumno;
	}

	public String getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(String idCiclo) {
		this.idCiclo = idCiclo;
	}

	public String getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(String modalidad) {
		this.modalidad = modalidad;
	}

	public int getCurso() {
		return this.curso;
	}

	public void setCurso(int curso) {
		this.curso = curso;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
